/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        "surface-container-highest": "#d3e4fe",
        "on-primary": "#ffffff",
        "on-secondary-container": "#5c647a",
        "secondary-fixed": "#dae2fd",
        "tertiary": "#005b7c",
        "surface": "#f8f9ff",
        "on-secondary-fixed": "#131b2e",
        "surface-bright": "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-container": "#eeefff",
        "surface-dim": "#cbdbf5",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#b4c5ff",
        "inverse-surface": "#213145",
        "on-error": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "on-tertiary-fixed": "#001e2c",
        "surface-tint": "#0053db",
        "on-error-container": "#93000a",
        "tertiary-container": "#00759f",
        "surface-container-low": "#eff4ff",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary-fixed": "#00174b",
        "outline-variant": "#c3c6d7",
        "surface-container-lowest": "#ffffff",
        "outline": "#737686",
        "secondary-container": "#dae2fd",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "primary": "#004ac6",
        "tertiary-fixed": "#c4e7ff",
        "on-background": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-high": "#dce9ff",
        "primary-container": "#2563eb",
        "error-container": "#ffdad6",
        "on-surface-variant": "#434655",
        "on-tertiary-fixed-variant": "#004c69",
        "secondary": "#565e74",
        "on-surface": "#0b1c30",
        "background": "#f8f9ff",
        "on-tertiary-container": "#e1f2ff",
        "on-secondary-fixed-variant": "#3f465c",
        "on-tertiary": "#ffffff",
        "surface-container": "#e5eeff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin": "2rem",
        "gutter": "1.5rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "space-3xl": "6rem",
        "margin-mobile": "1.25rem",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "display-hero": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-xl": ["Inter"],
        "label-caps": ["Inter"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "display-hero": ["64px", { lineHeight: "72px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-xl": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.005em", fontWeight: "400" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
      },
    },
  },
}
