/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          900: '#071224',
          800: '#0a192f',
          700: '#0f2442',
          600: '#1e3a5f',
          accent: '#38bdf8',
        },
        "tertiary-fixed-dim": "#68dba9",
        "secondary-fixed": "#d8e2ff",
        "inverse-on-surface": "#eaf1ff",
        "surface-container": "#e5eeff",
        "on-tertiary-fixed": "#002114",
        "on-secondary-fixed": "#091b39",
        "tertiary": "#000000",
        "secondary": "#4f5e80",
        "primary-fixed-dim": "#b9c7e4",
        "on-surface-variant": "#44474d",
        "tertiary-container": "#002114",
        "background": "#f8f9ff",
        "on-secondary-container": "#4e5d7e",
        "on-tertiary-container": "#069669",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed-variant": "#005137",
        "surface-dim": "#cbdbf5",
        "secondary-container": "#c7d7fe",
        "surface-container-low": "#eff4ff",
        "secondary-fixed-dim": "#b6c6ed",
        "on-error-container": "#93000a",
        "inverse-primary": "#b9c7e4",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d6e3ff",
        "on-primary": "#ffffff",
        "on-surface": "#0b1c30",
        "primary-container": "#0d1c32",
        "primary": "#000000",
        "on-primary-fixed": "#0d1c32",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed-variant": "#374767",
        "inverse-surface": "#213145",
        "surface-tint": "#515f78",
        "tertiary-fixed": "#85f8c4",
        "outline": "#75777e",
        "on-primary-container": "#76849f",
        "surface": "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-variant": "#d3e4fe",
        "outline-variant": "#c5c6cd",
        "on-background": "#0b1c30",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#39475f",
        "error": "#ba1a1a"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "sm": "0px",
        "md": "0px",
        "lg": "0px",
        "xl": "0px",
        "2xl": "0px",
        "3xl": "0px",
        "full": "0px"
      },
      spacing: {
        "margin-mobile": "1.25rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin": "3rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        "body-lg": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "display": ["Space Grotesk", "sans-serif"],
        "label-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["1.125rem", { "lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "label-sm": ["0.6875rem", { "lineHeight": "1", "letterSpacing": "0.06em", "fontWeight": "600" }],
        "headline-sm": ["1.125rem", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-lg-mobile": ["1.75rem", { "lineHeight": "1.25", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-md": ["0.9375rem", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-sm": ["0.8125rem", { "lineHeight": "1.45", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-md": ["1.5rem", { "lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "500" }],
        "headline-lg": ["2.25rem", { "lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "display": ["3.5rem", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600" }],
        "label-md": ["0.875rem", { "lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
}
