export * from './CollegeDepartments';
export * from './CollegePrograms';
export * from './CollegeBatches';
export * from './CollegeClasses';
export * from './CollegeSubjects';
export * from './ManageHods';
export * from './ManageFaculty';
export * from './ManageStudents';
export * from './CollegeProfile';
