export { default as facultyAiRoutes } from './facultyAi.routes';
export { facultyAiController, FacultyAiController } from './facultyAi.controller';
export { facultyAiOrchestratorService, FacultyAiOrchestratorService } from './facultyAi.service';
export {
  facultyToolRegistry,
  FacultyToolRegistry,
  FACULTY_TOOL_METADATA,
} from './toolRegistry';

export {
  FACULTY_TOOL_NAMES,
  type FacultyToolName,
  isFacultyToolName,
  type FacultyContext,
  toFacultyContext,
  type ChatRole,
  type ChatMessage,
  type FacultyChatRequest,
  type ToolExecutionResult,
  type FacultyChatResponseData,
  type ToolHandler,
  type ToolMetadata,
  // Tool I/O Types
  type FacultyGetDashboardInput,
  type FacultyGetDashboardOutput,
  type FacultyGetAssignedClassesInput,
  type FacultyGetAssignedClassesOutput,
  type FacultyGetClassDetailsInput,
  type FacultyGetClassDetailsOutput,
  type FacultyGetClassStudentsInput,
  type FacultyGetClassStudentsOutput,
  type FacultyGetStudentDetailsInput,
  type FacultyGetStudentDetailsOutput,
  type FacultyGetStudentAttendanceInput,
  type FacultyGetStudentAttendanceOutput,
  type FacultyGetClassAttendanceStatsInput,
  type FacultyGetClassAttendanceStatsOutput,
  type FacultyGetClassAttendanceHistoryInput,
  type FacultyGetClassAttendanceHistoryOutput,
  type FacultyGetClassTimetableInput,
  type FacultyGetClassTimetableOutput,
  type FacultyGetTimetableInput,
  type FacultyGetTimetableOutput,
  type FacultyGetRemindersInput,
  type FacultyGetRemindersOutput,
  type FacultySearchInput,
  type FacultySearchOutput,
  type FacultyGetDepartmentInput,
  type FacultyGetDepartmentOutput,
  type FacultyGetSubjectsInput,
  type FacultyGetSubjectsOutput,
  type FacultyGetAcademicYearsInput,
  type FacultyGetAcademicYearsOutput,
  type FacultyGetSemestersInput,
  type FacultyGetSemestersOutput,
  type FacultyGetPerformanceInput,
  type FacultyGetPerformanceOutput,
  type FacultySearchKnowledgeInput,
  type FacultySearchKnowledgeOutput,
  type FacultyGetKnowledgeContextInput,
  type FacultyGetKnowledgeContextOutput,
} from './facultyAi.types';

export {
  facultyChatRequestSchema,
  directToolExecutionSchema,
  TOOL_INPUT_SCHEMAS,
  TOOL_OUTPUT_SCHEMAS,
} from './facultyAi.validation';
